#!/usr/bin/env bash

######################################################################
# This script installs required dependencies for Torch7
######################################################################

install_openblas() {
    # Get and build OpenBlas (Torch is much better with a decent Blas)
    cd /tmp/
    git clone https://github.com/xianyi/OpenBLAS.git
    cd OpenBLAS
    if [ $(getconf _NPROCESSORS_ONLN) == 1 ]; then
        make NO_AFFINITY=1 USE_OPENMP=0 USE_THREAD=0
    else
        make NO_AFFINITY=1 USE_OPENMP=1
    fi
    RET=$?; 
    if [ $RET -ne 0 ]; then
        echo "Error. OpenBLAS could not be compiled";
        exit $RET;
    fi
    sudo make install
    RET=$?; 
    if [ $RET -ne 0 ]; then
        echo "Error. OpenBLAS could not be installed";
        exit $RET;
    fi
}

# Install dependencies for Torch:
if [[ "$(uname -m)" == 'ppc64le' ]]; then
        declare -a target_pkgs
        target_pkgs=( curl cmake build-essential gcc g++ \
            cmake libreadline-dev git-core libqt4-dev \
            libjpeg8-dev libpng12-dev libncurses5-dev \
            imagemagick gfortran unzip gnuplot libx11-dev \
            gnuplot-x11 ipython libfftw3-3 graphicsmagick \
            libmagickwand-dev libgraphicsmagick1-dev \
            libfftw3-dev sox libsox-dev libsox-fmt-all )
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo apt-get install -y "${target_pkgs[@]}"

        install_openblas
else
    # Unsupported
    echo '==> platform not supported, aborting'
    exit 1
fi

ipython_exists=$(command -v ipython)
if [[ $ipython_exists ]]; then {
    ipython_version=$(ipython --version|cut -f1 -d'.')
    if [[ $ipython_version != 2 && $ipython_version != 3 && $ipython_version != 4 ]]; then {
        echo 'WARNING: Your ipython version is too old.  Type "ipython --version" to see this.  Should be at least version 2'
    } fi
} fi

# Done.
echo "==> Torch7's dependencies have been installed"

